from pathlib import Path


SUSPICIOUS_PRODUCERS = {
    "Adobe Photoshop": {
        "severity": "CRITICAL",
        "reason_template": "Adobe Photoshop is a raster image editor, never used to generate financial instruments or official documents. Bank documents, salary slips, and legal certificates are produced by secure printing presses, payroll software, or government portals , not designed in Photoshop. This signature confirms the document was digitally fabricated as an image file.",
        "action_template": "Reject document. Contact issuing authority to verify authenticity through official channels.",
    },
    "Canva": {
        "severity": "HIGH",
        "reason_template": "Canva is a consumer graphic design web application primarily used for social media posts and marketing materials. Legitimate payroll software (SAP HCM, ADP, Keka HR, Darwinbox) and government portals never export to Canva format. The document was designed using Canva templates rather than generated by an authorized system.",
        "action_template": "Reject document. Request official document directly from the issuing organization or verify through government portal.",
    },
    "Microsoft Word": {
        "severity": "CAUTION",
        "reason_template": "Microsoft Word is acceptable for certain document types (appointment letters, internal memos) but not for financial instruments or government certificates. Verify that the issuing authority's standard practice includes Word-generated documents.",
        "action_template": "Cross-verify document with issuing authority's standard format. Request official letterhead version if available.",
    },
    "Paint": {
        "severity": "CRITICAL",
        "reason_template": "Microsoft Paint is a basic bitmap editor. No official document is ever generated using Paint. This indicates amateur digital fabrication.",
        "action_template": "Reject immediately. Document was created using consumer-grade image editing software.",
    },
    "Adobe Illustrator": {
        "severity": "HIGH",
        "reason_template": "Adobe Illustrator is a vector graphics editor used for graphic design, not for generating official financial or legal documents.",
        "action_template": "Verify document authenticity with issuing authority.",
    },
}

GOVERNMENT_PRODUCERS = {
    "nsdl", "itr", "income tax", "bbmp", "mca", "government",
    "e-governance", "portal", "pdf generator", "pdf writer",
}

GOVERNMENT_CREATORS = {
    "nsdl", "itr", "income tax", "bbmp", "mca", "government",
    "e-governance", "portal",
}

LEGIT_PRODUCERS_BY_DOC = {
    "cheque": {"bank cheque printing system", "secure print engine", "financial institution check printing"},
    "salary": {"sap", "adp", "keka", "darwinbox", "payroll", "hrms"},
    "itr": {"income tax department", "nsdl", "e-filing portal"},
    "kyc": {"kyc system", "financial institution kyc", "mca"},
    "plan_approval": {"bbmp", "e-governance", "municipal"},
    "occupancy_cert": {"bbmp", "e-governance", "municipal"},
    "rent": {"legal document service", "legaldocs", "rent agreement portal"},
    "appointment": {"microsoft word", "microsoft office", "hr system"},
    "ca_certificate": {"icaI", "chartered accountant", "ca portal"},
    "death_certificate": {"municipal", "registrar", "government"},
    "legal_heir": {"municipal", "registrar", "government"},
}


def _classify_pdf_metadata(meta: dict, doc_type: str) -> dict:
    producer = (meta.get("producer") or "").lower()
    creator = (meta.get("creator") or "").lower()
    
    meta["editing_software_detected"] = False
    meta["flagged_software"] = None
    meta["status_note"] = "No image-editing software detected in metadata."
    meta["severity"] = "INFO"
    meta["action"] = None
    meta["reason"] = None
    
    for name, info in SUSPICIOUS_PRODUCERS.items():
        if name.lower() in producer or name.lower() in creator:
            meta["editing_software_detected"] = True
            meta["flagged_software"] = name
            meta["severity"] = info["severity"]
            meta["reason"] = info["reason_template"]
            meta["action"] = info["action_template"]
            meta["status_note"] = (
                f"{info['severity']}: Image editing software ({name}) "
                f"detected in PDF metadata container"
            )
            return meta
    
    is_gov_producer = any(g in producer for g in GOVERNMENT_PRODUCERS)
    is_gov_creator = any(g in creator for g in GOVERNMENT_CREATORS)
    
    if is_gov_producer or is_gov_creator:
        meta["severity"] = "OK"
        meta["status_note"] = "Government portal-generated PDF, no editing software signatures."
        return meta
    
    expected = LEGIT_PRODUCERS_BY_DOC.get(doc_type, set())
    if expected:
        if any(e in producer for e in expected):
            meta["severity"] = "OK"
            meta["status_note"] = f"Expected producer detected ({producer}), no anomalies."
            return meta
    
    if producer and producer != "unknown / system generated":
        meta["editing_software_detected"] = True
        meta["flagged_software"] = producer
        meta["severity"] = "CAUTION"
        meta["status_note"] = (
            f"CAUTION: Producer '{producer}' does not match expected "
            f"patterns for '{doc_type}' documents. Manual review recommended."
        )
        meta["reason"] = f"Document producer '{producer}' is atypical for '{doc_type}' documents."
        meta["action"] = "Verify document authenticity with issuing authority."
    
    return meta


def extract_document_metadata(file_path: str, doc_type: str = "kyc") -> dict:
    path = Path(file_path)
    suffix = path.suffix.lower()

    meta = {
        "filename": path.name,
        "format": suffix.lstrip("."),
        "file_size_bytes": path.stat().st_size,
        "producer": None,
        "creator": None,
        "author": None,
        "n_pages": None,
        "editing_software_detected": False,
        "flagged_software": None,
        "severity": "INFO",
        "status_note": None,
        "reason": None,
        "action": None,
    }

    if suffix == ".pdf":
        try:
            import pypdf
            reader = pypdf.PdfReader(str(path))
            info = reader.metadata or {}
            meta["producer"] = info.get("/Producer", "Unknown / System Generated")
            meta["creator"] = info.get("/Creator", "Unknown")
            meta["author"] = info.get("/Author")
            meta["n_pages"] = len(reader.pages)
        except Exception:
            meta["producer"] = "Unknown / System Generated"
            meta["creator"] = "Unknown"
            meta["n_pages"] = 0
        return _classify_pdf_metadata(meta, doc_type)

    try:
        from PIL import Image as PILImage
        img = PILImage.open(str(path))
        exif = img.getexif() or {}
        software_tag = exif.get(305, "") or exif.get(11, "")
        if software_tag:
            meta["producer"] = software_tag
            meta["creator"] = software_tag
            meta["n_pages"] = 1
            img.close()
            return _classify_pdf_metadata(meta, doc_type)
        img.close()
    except Exception:
        pass

    meta["producer"] = "Unknown (scanned image)"
    meta["creator"] = "Unknown (scanned image)"
    meta["n_pages"] = 1
    meta["severity"] = "N/A"
    meta["status_note"] = "Hard-copy scan, PDF metadata not applicable."
    return meta
